export interface Product {
  id: string;
  name: string;
  category: ProductCategory;
  subcategory: string;
  brand: string;
  size: string;
  price: number;
  unit: 'kg' | 'ton' | 'piece';
  weight?: number; // وزن تقریبی برای هر شاخه
  description?: string;
  image?: string;
  inStock: boolean;
  lastUpdated: string;
  // فیلدهای تخصصی اختیاری
  thickness?: string; // برای ورق و نبشی
  diameter?: string; // برای لوله و سیم
  grade?: string; // درجه کیفیت
  coating?: string; // نوع پوشش/جنس
  standard?: string; // استاندارد
  length?: string; // طول
  // فیلدهای جدید
  subtype?: string; // نوع زیرمجموعه
  weightType?: string; // نوع وزن
  sheetType?: string; // نوع ورق
  pipeType?: string; // نوع لوله
  wireType?: string; // نوع سیم
  height?: string; // ارتفاع (برای تیرآهن)
  meshSize?: string; // سایز چشمه توری
  packageType?: string; // نوع بسته‌بندی
  // تاریخچه قیمت
  priceHistory?: {
    changeType: string;
    changeAmount: number;
    changedAt: string;
  };
}

export interface ProductCategory {
  id: string;
  name: string;
  slug?: string; // برای مقایسه با API response
  icon: string;
  subcategories: string[];
}

export interface PriceFilter {
  category?: string;
  subcategory?: string;
  brand?: string | string[]; // پشتیبانی از چندین برند
  size?: string | string[]; // پشتیبانی از چندین سایز
  minPrice?: number;
  maxPrice?: number;
  inStock?: boolean;
  // فیلترهای تخصصی
  thickness?: string | string[]; // برای ورق و نبشی
  diameter?: string | string[]; // برای لوله
  grade?: string | string[]; // درجه کیفیت
  coating?: string | string[]; // نوع پوشش (گالوانیزه، رنگی و...)
  standard?: string | string[]; // استاندارد (ملی، بین‌المللی)
  length?: string | string[]; // طول
  // فیلترهای جدید
  subtype?: string | string[]; // نوع زیرمجموعه (نبشی، ناودانی، سپری)
  weightType?: string | string[]; // نوع وزن (استاندارد، هم وزن اروپا)
  sheetType?: string | string[]; // نوع ورق (سیاه، گالوانیزه، رنگی، آجدار)
  pipeType?: string | string[]; // نوع لوله (داربستی، مانیسمان، گازی، اسپیرال)
  wireType?: string | string[]; // نوع سیم (سیاه، گالوانیزه، خاردار)
  height?: string | string[]; // ارتفاع (برای تیرآهن)
  meshSize?: string | string[]; // سایز چشمه توری
  packageType?: string | string[]; // نوع بسته‌بندی
}

export interface WeightCalculation {
  diameter: number;
  length: number;
  quantity: number;
  totalWeight: number;
}

// دسته‌بندی محصولات
export const PRODUCT_CATEGORIES: ProductCategory[] = [
  {
    id: 'rebar',
    name: 'میلگرد',
    icon: '🔩',
    subcategories: [
      'آجدار',
      'ساده',
      'کلاف',
      'حرارتی',
      'بستر',
      'ترانس',
      'استیل',
    ],
  },
  {
    id: 'profile',
    name: 'پروفیل',
    icon: '📐',
    subcategories: [
      'ساختمانی',
      'کنگره',
      'صنعتی',
      'Z',
      'گالوانیزه',
      'سبک',
      'استیل',
      'آلومینیوم',
      'UPE',
      'IPE',
      'HEA',
      'HEB',
    ],
  },
  {
    id: 'sheet',
    name: 'ورق',
    icon: '📋',
    subcategories: [
      'گرم',
      'سیاه',
      'سرد',
      'گالوانیزه',
      'رنگی',
      'استیل',
      'آلومینیوم',
      'مس',
    ],
  },
  {
    id: 'angle',
    name: 'نبشی و ناودانی',
    icon: '📏',
    subcategories: ['نبشی', 'ناودانی', 'سپری', 'گالوانیزه'],
  },
  {
    id: 'beam',
    name: 'تیرآهن',
    icon: '🏗️',
    subcategories: ['تیرآهن', 'هاش', 'لانه زنبوری', 'ریل', 'سنگین', 'سبک'],
  },
  {
    id: 'pipe',
    name: 'لوله',
    icon: '🔧',
    subcategories: [
      'درزدار',
      'بدون درز',
      'گالوانیزه',
      'استیل',
      'مس',
      'آلومینیوم',
      'پلی‌اتیلن',
      'PVC',
    ],
  },
  {
    id: 'wire',
    name: 'سیم',
    icon: '🧵',
    subcategories: ['سیم سیاه', 'سیم گالوانیزه', 'سیم خاردار', 'کابل'],
  },
  {
    id: 'mesh',
    name: 'توری',
    icon: '🕸️',
    subcategories: [
      'توری حصاری',
      'توری جوشی',
      'توری گالوانیزه',
      'توری پلاستیکی',
    ],
  },
  {
    id: 'shamsh',
    name: 'شمش',
    icon: '🧱',
    subcategories: ['فولاد', 'آلیاژی'],
  },
  {
    id: 'qooti',
    name: 'قوطی',
    icon: '📦',
    subcategories: ['صنعتی', 'ستونی'],
  },
  {
    id: 'maftoli',
    name: 'محصولات مفتولی',
    icon: '🔗',
    subcategories: [
      'سیم مفتولی سیاه',
      'سیم مفتولی گالوانیزه',
      'توری حصاری',
      'مش آجدار',
    ],
  },
  {
    id: 'raw-materials',
    name: 'مواد اولیه',
    icon: '⚗️',
    subcategories: ['آهن اسفنجی', 'فروآلیاژ'],
  },
];

// مسیرهای محصولات برای routing
export const PRODUCT_ROUTES = {
  // میلگرد
  'milgerd-ajdar': {
    category: 'rebar',
    subcategory: 'آجدار',
    name: 'میلگرد آجدار',
  },
  'milgerd-sade': {
    category: 'rebar',
    subcategory: 'ساده',
    name: 'میلگرد ساده',
  },
  'milgerd-kolaf': {
    category: 'rebar',
    subcategory: 'کلاف',
    name: 'میلگرد کلاف',
  },
  'milgerd-harati': {
    category: 'rebar',
    subcategory: 'حرارتی',
    name: 'میلگرد حرارتی',
  },
  'milgerd-bastar': {
    category: 'rebar',
    subcategory: 'بستر',
    name: 'میلگرد بستر',
  },
  'milgerd-trans': {
    category: 'rebar',
    subcategory: 'ترانس',
    name: 'میلگرد ترانس',
  },
  'milgerd-steel': {
    category: 'rebar',
    subcategory: 'استیل',
    name: 'میلگرد استیل',
  },

  // پروفیل
  'profile-sakhtmani': {
    category: 'profile',
    subcategory: 'ساختمانی',
    name: 'پروفیل ساختمانی',
  },
  'profile-kongre': {
    category: 'profile',
    subcategory: 'کنگره',
    name: 'پروفیل کنگره',
  },
  'profile-sanati': {
    category: 'profile',
    subcategory: 'صنعتی',
    name: 'پروفیل صنعتی',
  },
  'profile-z': { category: 'profile', subcategory: 'Z', name: 'پروفیل Z' },
  'profile-galvanize': {
    category: 'profile',
    subcategory: 'گالوانیزه',
    name: 'پروفیل گالوانیزه',
  },
  'profile-sabk': {
    category: 'profile',
    subcategory: 'سبک',
    name: 'پروفیل سبک',
  },
  'profile-steel': {
    category: 'profile',
    subcategory: 'استیل',
    name: 'پروفیل استیل',
  },
  'profile-aluminum': {
    category: 'profile',
    subcategory: 'آلومینیوم',
    name: 'پروفیل آلومینیوم',
  },
  'profile-upe': {
    category: 'profile',
    subcategory: 'UPE',
    name: 'پروفیل UPE',
  },
  'profile-ipe': {
    category: 'profile',
    subcategory: 'IPE',
    name: 'پروفیل IPE',
  },
  'profile-hea': {
    category: 'profile',
    subcategory: 'HEA',
    name: 'پروفیل HEA',
  },
  'profile-heb': {
    category: 'profile',
    subcategory: 'HEB',
    name: 'پروفیل HEB',
  },

  // ورق
  'varagh-garm': { category: 'sheet', subcategory: 'گرم', name: 'ورق گرم' },
  'varagh-siah': { category: 'sheet', subcategory: 'سیاه', name: 'ورق سیاه' },
  'varagh-sard': { category: 'sheet', subcategory: 'سرد', name: 'ورق سرد' },
  'varagh-galvanize': {
    category: 'sheet',
    subcategory: 'گالوانیزه',
    name: 'ورق گالوانیزه',
  },
  'varagh-rangi': { category: 'sheet', subcategory: 'رنگی', name: 'ورق رنگی' },
  'varagh-steel': {
    category: 'sheet',
    subcategory: 'استیل',
    name: 'ورق استیل',
  },
  'varagh-aluminum': {
    category: 'sheet',
    subcategory: 'آلومینیوم',
    name: 'ورق آلومینیوم',
  },
  'varagh-mes': { category: 'sheet', subcategory: 'مس', name: 'ورق مس' },

  // نبشی و ناودانی
  nabshi: { category: 'angle', subcategory: 'نبشی', name: 'نبشی' },
  navodani: { category: 'angle', subcategory: 'ناودانی', name: 'ناودانی' },
  separi: { category: 'angle', subcategory: 'سپری', name: 'سپری' },
  'nabshi-galvanize': {
    category: 'angle',
    subcategory: 'گالوانیزه',
    name: 'نبشی گالوانیزه',
  },

  // تیرآهن
  tirahan: { category: 'beam', subcategory: 'تیرآهن', name: 'تیرآهن' },
  hash: { category: 'beam', subcategory: 'هاش', name: 'هاش' },
  'lane-zanbori': {
    category: 'beam',
    subcategory: 'لانه زنبوری',
    name: 'لانه زنبوری',
  },
  rail: { category: 'beam', subcategory: 'ریل', name: 'ریل' },
  'tirahan-sangin': {
    category: 'beam',
    subcategory: 'سنگین',
    name: 'تیرآهن سنگین',
  },
  'tirahan-sabk': { category: 'beam', subcategory: 'سبک', name: 'تیرآهن سبک' },

  // لوله
  'lole-darzdar': {
    category: 'pipe',
    subcategory: 'درزدار',
    name: 'لوله درزدار',
  },
  'lole-bedone-darz': {
    category: 'pipe',
    subcategory: 'بدون درز',
    name: 'لوله بدون درز',
  },
  'lole-galvanize': {
    category: 'pipe',
    subcategory: 'گالوانیزه',
    name: 'لوله گالوانیزه',
  },
  'lole-steel': { category: 'pipe', subcategory: 'استیل', name: 'لوله استیل' },
  'lole-mes': { category: 'pipe', subcategory: 'مس', name: 'لوله مس' },
  'lole-aluminum': {
    category: 'pipe',
    subcategory: 'آلومینیوم',
    name: 'لوله آلومینیوم',
  },
  'lole-polyethylene': {
    category: 'pipe',
    subcategory: 'پلی‌اتیلن',
    name: 'لوله پلی‌اتیلن',
  },
  'lole-pvc': { category: 'pipe', subcategory: 'PVC', name: 'لوله PVC' },

  // سی��
  'sim-siah': { category: 'wire', subcategory: 'سیم سیاه', name: 'سیم سیاه' },
  'sim-galvanize': {
    category: 'wire',
    subcategory: 'سیم گالوانیزه',
    name: 'سیم گالوانیزه',
  },
  'sim-khardar': {
    category: 'wire',
    subcategory: 'سیم خاردار',
    name: 'سیم خاردار',
  },
  kabel: { category: 'wire', subcategory: 'کابل', name: 'کابل' },

  // توری
  'tori-hesari': {
    category: 'mesh',
    subcategory: 'توری حصاری',
    name: 'توری حصاری',
  },
  'tori-joshi': {
    category: 'mesh',
    subcategory: 'توری جوشی',
    name: 'توری جوشی',
  },
  'tori-galvanize': {
    category: 'mesh',
    subcategory: 'توری گالوانیزه',
    name: 'توری گالوانیزه',
  },
  'tori-plastic': {
    category: 'mesh',
    subcategory: 'توری پلاستیکی',
    name: 'توری پلاستیکی',
  },

  // شمش
  'shamsh-folad': {
    category: 'shamsh',
    subcategory: 'فولاد',
    name: 'شمش فولاد',
  },
  'shamsh-aliaazhi': {
    category: 'shamsh',
    subcategory: 'آلیاژی',
    name: 'شمش آلیاژی',
  },

  // قوطی
  'qooti-sanate': {
    category: 'qooti',
    subcategory: 'صنعتی',
    name: 'قوطی صنعتی',
  },
  'qooti-sotoni': {
    category: 'qooti',
    subcategory: 'ستونی',
    name: 'قوطی ستونی',
  },

  // محصولات مفتولی
  'sim-maftooli-siah': {
    category: 'maftoli',
    subcategory: 'سیم مفتولی سیاه',
    name: 'سیم مفتولی سیاه',
  },
  'sim-maftooli-galvanize': {
    category: 'maftoli',
    subcategory: 'سیم مفتولی گالوانیزه',
    name: 'سیم مفتولی گالوانیزه',
  },
  'toori-hesari': {
    category: 'maftoli',
    subcategory: 'توری حصاری',
    name: 'توری حصاری',
  },
  'mesh-ajdar': {
    category: 'maftoli',
    subcategory: 'مش آجدار',
    name: 'مش آجدار',
  },

  // مواد اولیه
  'ahan-esfonji': {
    category: 'raw-materials',
    subcategory: 'آهن اسفنجی',
    name: 'آهن اسفنجی',
  },
  'foro-aliazh': {
    category: 'raw-materials',
    subcategory: 'فروآلیاژ',
    name: 'فروآلیاژ',
  },
};

// برندهای معروف
export const BRANDS = [
  'اصفهان',
  'نیشابور',
  'میانه',
  'ظفر بناب',
  'فایکو',
  'راد همدان',
  'بافق',
  'آناهیتا',
  'زاگرس',
  'ابرکوه',
  'شاهرود',
  'شاهین بناب',
  'اهواز',
  'اروند',
  'آریان فولاد',
  'فولاد ثامن',
  'فولاد سپهر',
  'فولاد متین',
];

// سایزهای رایج میلگرد
export const REBAR_SIZES = [
  '8',
  '10',
  '12',
  '14',
  '16',
  '18',
  '20',
  '22',
  '25',
  '28',
  '32',
];

// سایزهای تیرآهن
export const BEAM_SIZES = [
  '10',
  '12',
  '14',
  '16',
  '18',
  '20',
  '22',
  '24',
  '27',
  '30',
];

// سایزهای قوطی
export const QOOTI_SIZES = [
  '20×20×2',
  '25×25×2',
  '30×30×3',
  '40×40×3',
  '50×50×4',
  '60×60×4',
  '80×80×5',
  '100×100×5',
  '120×120×6',
  '150×150×8',
];

// سایزهای سیم مفتولی
export const WIRE_SIZES = [
  '1mm',
  '1.5mm',
  '2mm',
  '2.5mm',
  '3mm',
  '4mm',
  '5mm',
  '6mm',
  '8mm',
];

// ابعاد شمش
export const SHAMSH_SIZES = [
  '50kg',
  '100kg',
  '150kg',
  '200kg',
  '250kg',
  '300kg',
];

// ابعاد مش
export const MESH_SIZES = [
  '100×100×6',
  '150×150×6',
  '150×150×8',
  '200×200×8',
  '200×200×10',
];

// نمونه محصولات
export const SAMPLE_PRODUCTS: Product[] = [
  // میلگرد آجدار
  {
    id: 'rebar-8-isfahan',
    name: 'میلگرد آجدار 8',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '8',
    price: 182000,
    unit: 'kg',
    weight: 0.395,
    description: 'میلگرد آجدار سایز 8 برند اصفهان - مطابق استاندارد ملی ایران',
    inStock: true,
    lastUpdated: '2025-09-15',
    grade: 'A3',
    length: '12',
  },
  {
    id: 'rebar-10-isfahan',
    name: 'میلگرد آجدار 10',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '10',
    price: 183000,
    unit: 'kg',
    weight: 0.617,
    description: 'میلگرد آجدار سایز 10 برند اصفهان - کیفیت A3',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-12-isfahan',
    name: 'میلگرد آجدار 12',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '12',
    price: 184000,
    unit: 'kg',
    weight: 0.888,
    description: 'میلگرد آجدار سایز 12 برند اصفهان - مقاوم در برابر زلزله',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-14-isfahan',
    name: 'میلگرد آجدار 14',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '14',
    price: 185000,
    unit: 'kg',
    weight: 1.21,
    description: 'میلگرد آجدار سایز 14 برند اصفهان - استاندارد ASTM',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-16-isfahan',
    name: 'میلگرد آجدار 16',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '16',
    price: 186000,
    unit: 'kg',
    weight: 1.58,
    description: 'میلگرد آجدار سایز 16 برند اصفهان - مناسب برای سازه‌های بتنی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-18-isfahan',
    name: 'میلگرد آجدار 18',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '18',
    price: 187000,
    unit: 'kg',
    weight: 2.0,
    description: 'میلگرد آجدار سایز 18 برند اصفهان - کیفیت فوق‌العاده',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-20-isfahan',
    name: 'میلگرد آجدار 20',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '20',
    price: 188000,
    unit: 'kg',
    weight: 2.47,
    description: 'میلگرد آجدار سایز 20 برند اصفهان - مقاومت بالا',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-22-isfahan',
    name: 'میلگرد آجدار 22',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '22',
    price: 189000,
    unit: 'kg',
    weight: 2.98,
    description: 'میلگرد آجدار سایز 22 برند اصفهان - برای پروژه‌های بزرگ',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-25-isfahan',
    name: 'میلگرد آجدار 25',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'اصفهان',
    size: '25',
    price: 190000,
    unit: 'kg',
    weight: 3.85,
    description: 'میلگرد آجدار سایز 25 برند اصفهان - سنگین‌ترین سایز',
    inStock: true,
    lastUpdated: '2025-09-15',
  },

  // میلگرد نیشابور
  {
    id: 'rebar-12-nishabur',
    name: 'میلگرد آجدار 12',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'نیشابور',
    size: '12',
    price: 183500,
    unit: 'kg',
    weight: 0.888,
    description: 'میلگرد آجدار سایز 12 برند نیشابور - کیفیت ممتاز',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-14-nishabur',
    name: 'میلگرد آجدار 14',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'نیشابور',
    size: '14',
    price: 184500,
    unit: 'kg',
    weight: 1.21,
    description: 'میلگرد آجدار سایز 14 برند نیشابور - مقاومت عالی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-16-nishabur',
    name: 'میلگرد آجدار 16',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'نیشابور',
    size: '16',
    price: 185500,
    unit: 'kg',
    weight: 1.58,
    description: 'میلگرد آجدار سایز 16 برند نیشابور - استاندارد بین‌المللی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-18-nishabur',
    name: 'میلگرد آجدار 18',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'نیشابور',
    size: '18',
    price: 186500,
    unit: 'kg',
    weight: 2.0,
    description: 'میلگرد آجدار سایز 18 برند نیشابور - برای سازه‌های مقاوم',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-20-nishabur',
    name: 'میلگرد آجدار 20',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'آجدار',
    brand: 'نیشابور',
    size: '20',
    price: 187500,
    unit: 'kg',
    weight: 2.47,
    description: 'میلگرد آجدار سایز 20 برند نیشابور - کیفیت برتر',
    inStock: true,
    lastUpdated: '2025-09-15',
  },

  // میلگرد ساده
  {
    id: 'rebar-simple-8-isfahan',
    name: 'میلگرد ساده 8',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'ساده',
    brand: 'اصفهان',
    size: '8',
    price: 178000,
    unit: 'kg',
    weight: 0.395,
    description: 'میلگرد ساده سایز 8 برند اصفهان - مناسب برای کاربردهای عمومی',
    inStock: true,
    lastUpdated: '2025-09-15',
    grade: 'A2',
    length: '12',
  },
  {
    id: 'rebar-simple-10-isfahan',
    name: 'میلگرد ساده 10',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'ساده',
    brand: 'اصفهان',
    size: '10',
    price: 179000,
    unit: 'kg',
    weight: 0.617,
    description: 'میلگرد ساده سایز 10 برند اصفهان - اقتصادی و با کیفیت',
    inStock: true,
    lastUpdated: '2025-09-15',
    grade: 'A2',
    length: '6',
  },
  {
    id: 'rebar-simple-12-isfahan',
    name: 'میلگرد ساده 12',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'ساده',
    brand: 'اصفهان',
    size: '12',
    price: 180000,
    unit: 'kg',
    weight: 0.888,
    description: 'میلگرد ساده سایز 12 برند اصفهان - مناسب برای آرماتوربندی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-simple-14-isfahan',
    name: 'میلگرد ساده 14',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'ساده',
    brand: 'اصفهان',
    size: '14',
    price: 181000,
    unit: 'kg',
    weight: 1.21,
    description: 'میلگرد ساده سایز 14 برند اصفهان - مقاومت مناسب',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'rebar-simple-16-isfahan',
    name: 'میلگرد ساده 16',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'ساده',
    brand: 'اصفهان',
    size: '16',
    price: 182000,
    unit: 'kg',
    weight: 1.58,
    description: 'میلگرد ساده سایز 16 برند اصفهان - برای سازه‌های سبک',
    inStock: true,
    lastUpdated: '2025-09-15',
  },

  // میلگرد کلاف
  {
    id: 'rebar-kolaf-8-isfahan',
    name: 'میلگرد کلاف 8',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'کلاف',
    brand: 'اصفهان',
    size: '8',
    price: 180000,
    unit: 'kg',
    weight: 0.395,
    description: 'میلگرد کلاف سایز 8 برند اصفهان - بسته‌بندی حلقه‌ای',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-kolaf-10-isfahan',
    name: 'میلگرد کلاف 10',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'کلاف',
    brand: 'اصفهان',
    size: '10',
    price: 181000,
    unit: 'kg',
    weight: 0.617,
    description: 'میلگرد کلاف سایز 10 برند اصفهان - مناسب برای خمکاری',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-kolaf-12-isfahan',
    name: 'میلگرد کلاف 12',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'کلاف',
    brand: 'اصفهان',
    size: '12',
    price: 182000,
    unit: 'kg',
    weight: 0.888,
    description: 'میلگرد کلاف سایز 12 برند اصفهان - قابلیت انعطاف بالا',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // میلگرد حرارتی
  {
    id: 'rebar-harati-10-foolad-khuzestan',
    name: 'میلگرد حرارتی 10',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'حرارتی',
    brand: 'فولاد خوزستان',
    size: '10',
    price: 195000,
    unit: 'kg',
    weight: 0.617,
    description:
      'میلگرد حرارتی سایز 10 برند فولاد خوزستان - مقاومت در برابر زلزله بالا',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-harati-12-foolad-khuzestan',
    name: 'میلگرد حرارتی 12',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'حرارتی',
    brand: 'فولاد خوزستان',
    size: '12',
    price: 196000,
    unit: 'kg',
    weight: 0.888,
    description: 'میلگرد حرارتی سایز 12 برند فولاد خوزستان - کیفیت ویژه',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-harati-14-foolad-khuzestan',
    name: 'میلگرد حرارتی 14',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'حرارتی',
    brand: 'فولاد خوزستان',
    size: '14',
    price: 197000,
    unit: 'kg',
    weight: 1.21,
    description:
      'میلگرد حرارتی سایز 14 برند فولاد خوزستان - استاندارد بین‌المللی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-harati-16-foolad-khuzestan',
    name: 'میلگرد حرارتی 16',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'حرارتی',
    brand: 'فولاد خوزستان',
    size: '16',
    price: 198000,
    unit: 'kg',
    weight: 1.58,
    description: 'میلگرد حرارتی سایز 16 برند فولاد خوزستان - مقاومت فوق‌العاده',
    inStock: false,
    lastUpdated: '2025-10-04',
  },

  // میلگرد بستر
  {
    id: 'rebar-bastar-8-mobarakeh',
    name: 'میلگرد بستر 8',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'بستر',
    brand: 'مبارکه',
    size: '8',
    price: 175000,
    unit: 'kg',
    weight: 0.395,
    description: 'میلگرد بستر سایز 8 برند مبارکه - مناسب برای دال‌سازی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-bastar-10-mobarakeh',
    name: 'میلگرد بستر 10',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'بستر',
    brand: 'مبارکه',
    size: '10',
    price: 176000,
    unit: 'kg',
    weight: 0.617,
    description: 'میلگرد بستر سایز 10 برند مبارکه - کیفیت عالی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // میلگرد ترانس
  {
    id: 'rebar-trans-12-zob-ahan',
    name: 'میلگرد ترانس 12',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'ترانس',
    brand: 'ذوب آهن',
    size: '12',
    price: 205000,
    unit: 'kg',
    weight: 0.888,
    description: 'میلگرد ترانس سایز 12 برند ذوب آهن - مخصوص ترانسفورماتور',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-trans-14-zob-ahan',
    name: 'میلگرد ترانس 14',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'ترانس',
    brand: 'ذوب آهن',
    size: '14',
    price: 206000,
    unit: 'kg',
    weight: 1.21,
    description: 'میلگرد ترانس سایز 14 برند ذوب آهن - خاص صنایع برق',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // میلگرد استیل
  {
    id: 'rebar-steel-8-kaveh',
    name: 'میلگرد استیل 8',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'استیل',
    brand: 'کاوه',
    size: '8',
    price: 285000,
    unit: 'kg',
    weight: 0.395,
    description: 'میلگرد استیل سایز 8 برند کاوه - ضد زنگ و مقاوم',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-steel-10-kaveh',
    name: 'میلگرد استیل 10',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'استیل',
    brand: 'کاوه',
    size: '10',
    price: 287000,
    unit: 'kg',
    weight: 0.617,
    description: 'میلگرد استیل سایز 10 برند کاوه - کیفیت بین‌المللی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'rebar-steel-12-kaveh',
    name: 'میلگرد استیل 12',
    category: PRODUCT_CATEGORIES[0],
    subcategory: 'استیل',
    brand: 'کاوه',
    size: '12',
    price: 289000,
    unit: 'kg',
    weight: 0.888,
    description: 'میلگرد استیل سایز 12 برند کاوه - مناسب برای محیط‌های خورنده',
    inStock: false,
    lastUpdated: '2025-10-04',
  },

  // پروفیل ساختمانی
  {
    id: 'profile-sakhtmani-upe-80-fayko',
    name: 'پروفیل UPE 80',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'ساختمانی',
    brand: 'فایکو',
    size: 'UPE 80',
    price: 201000,
    unit: 'kg',
    weight: 6.0,
    description: 'پروفیل UPE سایز 80 برند فایکو - مناسب برای ستون‌سازی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-sakhtmani-upe-100-fayko',
    name: 'پروفیل UPE 100',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'ساختمانی',
    brand: 'فایکو',
    size: 'UPE 100',
    price: 202000,
    unit: 'kg',
    weight: 8.5,
    description: 'پروفیل UPE سایز 100 برند فایکو - کیفیت صنعتی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-sakhtmani-upe-120-fayko',
    name: 'پروفیل UPE 120',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'ساختمانی',
    brand: 'فایکو',
    size: 'UPE 120',
    price: 203000,
    unit: 'kg',
    weight: 10.4,
    description: 'پروفیل UPE سایز 120 برند فایکو - مقاومت بالا',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-sakhtmani-upe-140-fayko',
    name: 'پروفیل UPE 140',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'ساختمانی',
    brand: 'فایکو',
    size: 'UPE 140',
    price: 204000,
    unit: 'kg',
    weight: 12.9,
    description: 'پروفیل UPE سایز 140 برند فایکو - برای سازه‌های سنگین',
    inStock: false,
    lastUpdated: '2025-10-04',
  },

  // پروفیل کنگره
  {
    id: 'profile-kongre-c-60-apadana',
    name: 'پروفیل کنگره C60',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'کنگره',
    brand: 'آپادانا',
    size: 'C60',
    price: 195000,
    unit: 'kg',
    weight: 1.8,
    description: 'پروفیل کنگره C60 برند آپادانا - مناسب برای دیوار کاذب',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-kongre-c-75-apadana',
    name: 'پروفیل کنگره C75',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'کنگره',
    brand: 'آپادانا',
    size: 'C75',
    price: 196000,
    unit: 'kg',
    weight: 2.25,
    description: 'پروفیل کنگره C75 برند آپادانا - استاندارد کنگره',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-kongre-u-50-apadana',
    name: 'پروفیل کنگره U50',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'کنگره',
    brand: 'آپادانا',
    size: 'U50',
    price: 194000,
    unit: 'kg',
    weight: 1.5,
    description: 'پروفیل کنگره U50 برند آپادانا - مناسب برای راهنما',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // پروفیل صنعتی
  {
    id: 'profile-sanati-ipe-120-mobarakeh',
    name: 'پروفیل IPE 120',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'صنعتی',
    brand: 'مبارکه',
    size: 'IPE 120',
    price: 210000,
    unit: 'kg',
    weight: 10.4,
    description: 'پروفیل IPE 120 برند مبارکه - استاندارد اروپایی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-sanati-ipe-140-mobarakeh',
    name: 'پروفیل IPE 140',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'صنعتی',
    brand: 'مبارکه',
    size: 'IPE 140',
    price: 212000,
    unit: 'kg',
    weight: 12.9,
    description: 'پروفیل IPE 140 برند مبارکه - مقاومت فوق‌العاده',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-sanati-ipe-160-mobarakeh',
    name: 'پروفیل IPE 160',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'صنعتی',
    brand: 'مبارکه',
    size: 'IPE 160',
    price: 214000,
    unit: 'kg',
    weight: 15.8,
    description: 'پروفیل IPE 160 برند مبارکه - برای پل‌ها و سازه‌های بزرگ',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // پروفیل Z
  {
    id: 'profile-z-100-galvanize-kaveh',
    name: 'پروفیل Z 100',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'Z',
    brand: 'کاوه',
    size: 'Z100',
    price: 218000,
    unit: 'kg',
    weight: 3.2,
    description: 'پروفیل Z 100 گالوانیزه برند کاوه - مقاوم در برابر خوردگی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-z-150-galvanize-kaveh',
    name: 'پروفیل Z 150',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'Z',
    brand: 'کاوه',
    size: 'Z150',
    price: 220000,
    unit: 'kg',
    weight: 4.8,
    description: 'پروفیل Z 150 گالوانیزه برند کاوه - برای سقف‌های شیبدار',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-z-200-galvanize-kaveh',
    name: 'پروفیل Z 200',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'Z',
    brand: 'کاوه',
    size: 'Z200',
    price: 222000,
    unit: 'kg',
    weight: 6.4,
    description: 'پروفیل Z 200 گالوانیزه برند کاوه - استحکام بالا',
    inStock: false,
    lastUpdated: '2025-10-04',
  },

  // پروفیل گالوانیزه
  {
    id: 'profile-galvanize-c-75-parsian',
    name: 'پروفیل گالوانیزه C75',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'گالوانیزه',
    brand: 'پارسیان',
    size: 'C75',
    price: 205000,
    unit: 'kg',
    weight: 2.25,
    description: 'پروفیل گالوانیزه C75 برند پارسیان - ضد زنگ',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-galvanize-u-75-parsian',
    name: 'پروفیل گالوانیزه U75',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'گالوانیزه',
    brand: 'پارسیان',
    size: 'U75',
    price: 206000,
    unit: 'kg',
    weight: 2.4,
    description: 'پروفیل گالوانیزه U75 برند پارسیان - مقاوم در برابر آب و هوا',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // پروفیل سبک
  {
    id: 'profile-sabk-cfs-70-sepahan',
    name: 'پروفیل سبک CFS 70',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'سبک',
    brand: 'سپاهان',
    size: 'CFS 70',
    price: 190000,
    unit: 'kg',
    weight: 1.2,
    description: 'پروفیل سبک CFS 70 برند سپاهان - مناسب برای LSF',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-sabk-cfs-100-sepahan',
    name: 'پروفیل سبک CFS 100',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'سبک',
    brand: 'سپاهان',
    size: 'CFS 100',
    price: 192000,
    unit: 'kg',
    weight: 1.8,
    description: 'پروفیل سبک CFS 100 برند سپاهان - وزن کم و استحکام بالا',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // پروفیل استیل
  {
    id: 'profile-steel-box-40x40-kaveh',
    name: 'پروفیل استیل باکس 40×40',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'استیل',
    brand: 'کاوه',
    size: '40×40×2',
    price: 320000,
    unit: 'kg',
    weight: 2.4,
    description: 'پروفیل استیل باکس 40×40 برند کاوه - ضد زنگ کامل',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-steel-box-50x50-kaveh',
    name: 'پروفیل استیل باکس 50×50',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'استیل',
    brand: 'کاوه',
    size: '50×50×3',
    price: 325000,
    unit: 'kg',
    weight: 4.47,
    description: 'پروفیل استیل باکس 50×50 برند کاوه - کیفیت صادراتی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // پروفیل آلومینیوم
  {
    id: 'profile-aluminum-box-40x40-irana',
    name: 'پروفیل آلومینیوم باکس 40×40',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'آلومینیوم',
    brand: 'ایرانا',
    size: '40×40×2',
    price: 285000,
    unit: 'kg',
    weight: 0.86,
    description: 'پروفیل آلومینیوم باکس 40×40 برند ایرانا - سبک و مقاوم',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-aluminum-u-50-irana',
    name: 'پروفیل آلومینیوم U50',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'آلومینیوم',
    brand: 'ایرانا',
    size: 'U50',
    price: 290000,
    unit: 'kg',
    weight: 0.65,
    description: 'پروفیل آلومینیوم U50 برند ایرانا - مناسب برای نما',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // پروفیل UPE
  {
    id: 'profile-upe-200-fooladazin',
    name: 'پروفیل UPE 200',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'UPE',
    brand: 'فولادآذین',
    size: 'UPE 200',
    price: 208000,
    unit: 'kg',
    weight: 18.8,
    description: 'پروفیل UPE 200 برند فولادآذین - برای ستون‌های سنگین',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-upe-240-fooladazin',
    name: 'پروفیل UPE 240',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'UPE',
    brand: 'فولادآذین',
    size: 'UPE 240',
    price: 210000,
    unit: 'kg',
    weight: 25.2,
    description: 'پروفیل UPE 240 برند فولادآذین - مقاومت فوق‌العاده',
    inStock: false,
    lastUpdated: '2025-10-04',
  },

  // پروفیل IPE
  {
    id: 'profile-ipe-180-arfa',
    name: 'پروفیل IPE 180',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'IPE',
    brand: 'آرفا',
    size: 'IPE 180',
    price: 216000,
    unit: 'kg',
    weight: 18.8,
    description: 'پروفیل IPE 180 برند آرفا - استاندارد اروپایی',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-ipe-200-arfa',
    name: 'پروفیل IPE 200',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'IPE',
    brand: 'آرفا',
    size: 'IPE 200',
    price: 218000,
    unit: 'kg',
    weight: 22.4,
    description: 'پروفیل IPE 200 برند آرفا - مناسب برای تیر',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // پروفیل HEA
  {
    id: 'profile-hea-120-foolad-sabalan',
    name: 'پروفیل HEA 120',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'HEA',
    brand: 'فولاد سبلان',
    size: 'HEA 120',
    price: 220000,
    unit: 'kg',
    weight: 19.9,
    description: 'پروفیل HEA 120 برند فولاد سبلان - سری سبک',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-hea-140-foolad-sabalan',
    name: 'پروفیل HEA 140',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'HEA',
    brand: 'فولاد سبلان',
    size: 'HEA 140',
    price: 222000,
    unit: 'kg',
    weight: 24.7,
    description: 'پروفیل HEA 140 برند فولاد سبلان - مقاومت بالا',
    inStock: true,
    lastUpdated: '2025-10-04',
  },

  // پروفیل HEB
  {
    id: 'profile-heb-120-foolad-sabalan',
    name: 'پروفیل HEB 120',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'HEB',
    brand: 'فولاد سبلان',
    size: 'HEB 120',
    price: 225000,
    unit: 'kg',
    weight: 26.7,
    description: 'پروفیل HEB 120 برند فولاد سبلان - سری سنگین',
    inStock: true,
    lastUpdated: '2025-10-04',
  },
  {
    id: 'profile-heb-140-foolad-sabalan',
    name: 'پروفیل HEB 140',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'HEB',
    brand: 'فولاد سبلان',
    size: 'HEB 140',
    price: 227000,
    unit: 'kg',
    weight: 33.7,
    description: 'پروفیل HEB 140 برند فولاد سبلان - برای سازه‌های صنعتی',
    inStock: false,
    lastUpdated: '2025-10-04',
  },

  // تیرآهن
  {
    id: 'beam-10-fayko',
    name: 'تیرآهن 10',
    category: PRODUCT_CATEGORIES[4],
    subcategory: 'تیرآهن',
    brand: 'فایکو',
    size: '10',
    price: 192000,
    unit: 'kg',
    weight: 8.0,
    description: 'تیرآهن سایز 10 برند فایکو - مناسب برای سازه‌های سبک',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'beam-12-fayko',
    name: 'تیرآهن 12',
    category: PRODUCT_CATEGORIES[4],
    subcategory: 'تیرآهن',
    brand: 'فایکو',
    size: '12',
    price: 193000,
    unit: 'kg',
    weight: 11.5,
    description: 'تیرآهن سایز 12 برند فایکو - کیفیت استاندارد اروپا',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'beam-14-fayko',
    name: 'تیرآهن 14',
    category: PRODUCT_CATEGORIES[4],
    subcategory: 'تیرآهن',
    brand: 'فایکو',
    size: '14',
    price: 194000,
    unit: 'kg',
    weight: 15.6,
    description: 'تیرآهن سایز 14 برند فایکو - مقاومت بالا در برابر خمش',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'beam-16-fayko',
    name: 'تیرآهن 16',
    category: PRODUCT_CATEGORIES[4],
    subcategory: 'تیرآهن',
    brand: 'فایکو',
    size: '16',
    price: 195000,
    unit: 'kg',
    weight: 20.4,
    description: 'تیرآهن سایز 16 برند فایکو - برای ساختمان‌های متوسط',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'beam-18-fayko',
    name: 'تیرآهن 18',
    category: PRODUCT_CATEGORIES[4],
    subcategory: 'تیرآهن',
    brand: 'فایکو',
    size: '18',
    price: 196000,
    unit: 'kg',
    weight: 25.7,
    description: 'تیرآهن سایز 18 برند فایکو - مناسب برای پل‌ها و سازه‌های بزرگ',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'beam-20-fayko',
    name: 'تیرآهن 20',
    category: PRODUCT_CATEGORIES[4],
    subcategory: 'تیرآهن',
    brand: 'فایکو',
    size: '20',
    price: 197000,
    unit: 'kg',
    weight: 31.4,
    description: 'تیرآهن سایز 20 برند فایکو - قدرت تحمل فوق‌العاده',
    inStock: true,
    lastUpdated: '2025-09-15',
  },

  // ورق
  {
    id: 'sheet-1mm-black',
    name: 'ورق سیاه 1 میلیمتر',
    category: PRODUCT_CATEGORIES[2],
    subcategory: 'سیاه',
    brand: 'فولاد ثامن',
    size: '1mm',
    price: 205000,
    unit: 'kg',
    description: 'ورق سیاه ضخامت 1 میلیمتر - مناسب برای کاربردهای صنعتی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'sheet-2mm-black',
    name: 'ورق سیاه 2 میلیمتر',
    category: PRODUCT_CATEGORIES[2],
    subcategory: 'سیاه',
    brand: 'فولاد ثامن',
    size: '2mm',
    price: 210000,
    unit: 'kg',
    description: 'ورق سیاه ضخامت 2 میلیمتر - کیفیت بالا و قیمت مناسب',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'sheet-3mm-galvanized',
    name: 'ورق گالوانیزه 3 میلیمتر',
    category: PRODUCT_CATEGORIES[2],
    subcategory: 'گالوانیزه',
    brand: 'فولاد ثامن',
    size: '3mm',
    price: 220000,
    unit: 'kg',
    description: 'ورق گالوانیزه ضخامت 3 میلیمتر - مقاوم در برابر زنگ',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'sheet-4mm-galvanized',
    name: 'ورق گالوانیزه 4 میلیمتر',
    category: PRODUCT_CATEGORIES[2],
    subcategory: 'گالوانیزه',
    brand: 'فولاد ثامن',
    size: '4mm',
    price: 225000,
    unit: 'kg',
    description: 'ورق گالوانیزه ضخامت 4 میلیمتر - عمر مفید طولانی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },

  // نبشی
  {
    id: 'angle-30x30x3',
    name: 'نبشی 30×30×3',
    category: PRODUCT_CATEGORIES[3],
    subcategory: 'نبشی',
    brand: 'اصفهان',
    size: '30×30×3',
    price: 198000,
    unit: 'kg',
    weight: 1.39,
    description: 'نبشی سایز 30×30×3 برند اصفهان - مناسب برای قاب‌سازی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'angle-40x40x4',
    name: 'نبشی 40×40×4',
    category: PRODUCT_CATEGORIES[3],
    subcategory: 'نبشی',
    brand: 'اصفهان',
    size: '40×40×4',
    price: 199000,
    unit: 'kg',
    weight: 2.42,
    description: 'نبشی سایز 40×40×4 برند اصفهان - استحکام بالا',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'angle-50x50x5',
    name: 'نبشی 50×50×5',
    category: PRODUCT_CATEGORIES[3],
    subcategory: 'نبشی',
    brand: 'اصفهان',
    size: '50×50×5',
    price: 200000,
    unit: 'kg',
    weight: 3.77,
    description: 'نبشی سایز 50×50×5 برند اصفهان - برای سازه‌های سنگین',
    inStock: true,
    lastUpdated: '2025-09-15',
  },

  // پروفیل
  {
    id: 'profile-upe-80',
    name: 'پروفیل UPE 80',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'ساختمانی',
    brand: 'فایکو',
    size: 'UPE 80',
    price: 201000,
    unit: 'kg',
    weight: 6.0,
    description: 'پروفیل UPE سایز 80 برند فایکو - مناسب برای ستون‌سازی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'profile-upe-100',
    name: 'پروفیل UPE 100',
    category: PRODUCT_CATEGORIES[1],
    subcategory: 'ساختمانی',
    brand: 'فایکو',
    size: 'UPE 100',
    price: 202000,
    unit: 'kg',
    weight: 8.5,
    description: 'پروفیل UPE سایز 100 برند فایکو - کیفیت صنعتی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },

  // لوله
  {
    id: 'pipe-1-inch',
    name: 'لوله گالوانیزه 1 اینچ',
    category: PRODUCT_CATEGORIES[5],
    subcategory: 'گالوانیزه',
    brand: 'اهواز',
    size: '1 اینچ',
    price: 215000,
    unit: 'kg',
    description:
      'لوله گالوانیزه سایز 1 اینچ برند اهواز - مقاوم در برابر خورندگی',
    inStock: true,
    lastUpdated: '2025-09-15',
  },
  {
    id: 'pipe-2-inch',
    name: 'لوله گالوانیزه 2 اینچ',
    category: PRODUCT_CATEGORIES[5],
    subcategory: 'گالوانیزه',
    brand: 'اهواز',
    size: '2 اینچ',
    price: 218000,
    unit: 'kg',
    description: 'لوله گالوانیزه سایز 2 اینچ برند اهواز - برای تاسیسات ساختمان',
    inStock: true,
    lastUpdated: '2025-09-15',
  },

  // شمش
  {
    id: 'shamsh-folad-150kg',
    name: 'شمش فولاد 150 کیلوگرم',
    category: PRODUCT_CATEGORIES[8],
    subcategory: 'فولاد',
    brand: 'اصفهان',
    size: '150kg',
    price: 165000,
    unit: 'kg',
    description: 'شمش فولاد درجه یک - مناسب برای تولید ورق و پروفیل',
    inStock: true,
    lastUpdated: '2025-09-30',
  },
  {
    id: 'shamsh-aliaazhi-100kg',
    name: 'شمش آلیاژی 100 کیلوگرم',
    category: PRODUCT_CATEGORIES[8],
    subcategory: 'آلیاژی',
    brand: 'فولاد ثامن',
    size: '100kg',
    price: 285000,
    unit: 'kg',
    description: 'شمش آلیاژی ضد زنگ - کیفیت صادراتی',
    inStock: true,
    lastUpdated: '2025-09-30',
  },

  // قوطی
  {
    id: 'qooti-sanate-40x40x3',
    name: 'قوطی صنعتی 40×40×3',
    category: PRODUCT_CATEGORIES[9],
    subcategory: 'صنعتی',
    brand: 'فایکو',
    size: '40×40×3',
    price: 192000,
    unit: 'kg',
    weight: 4.47,
    description: 'قوطی صنعتی مربع - مناسب برای سازه های فلزی',
    inStock: true,
    lastUpdated: '2025-09-30',
  },
  {
    id: 'qooti-sotoni-100x100x5',
    name: 'قوطی ستونی 100×100×5',
    category: PRODUCT_CATEGORIES[9],
    subcategory: 'ستونی',
    brand: 'اصفهان',
    size: '100×100×5',
    price: 198000,
    unit: 'kg',
    weight: 15.04,
    description: 'قوطی ستونی مقاوم - برای ستون سازی ساختمان',
    inStock: true,
    lastUpdated: '2025-09-30',
  },

  // محصولات مفتولی
  {
    id: 'sim-maftooli-siah-3mm',
    name: 'سیم مفتولی سیاه 3 میلیمتر',
    category: PRODUCT_CATEGORIES[10],
    subcategory: 'سیم مفتولی سیاه',
    brand: 'اصفهان',
    size: '3mm',
    price: 168000,
    unit: 'kg',
    description: 'سیم مفتولی سیاه کیفیت عالی - بسته بندی حلقه ای',
    inStock: true,
    lastUpdated: '2025-09-30',
  },
  {
    id: 'sim-maftooli-galvanize-4mm',
    name: 'سیم مفتولی گالوانیزه 4 میلیمتر',
    category: PRODUCT_CATEGORIES[10],
    subcategory: 'سیم مفتولی گالوانیزه',
    brand: 'نیشابور',
    size: '4mm',
    price: 185000,
    unit: 'kg',
    description: 'سیم مفتولی گالوانیزه - مقاوم در برابر خوردگی',
    inStock: true,
    lastUpdated: '2025-09-30',
  },
  {
    id: 'toori-hesari-50x50',
    name: 'توری حصاری 50×50',
    category: PRODUCT_CATEGORIES[10],
    subcategory: 'توری حصاری',
    brand: 'میانه',
    size: '50×50',
    price: 175000,
    unit: 'kg',
    description: 'توری حصاری گالوانیزه - ارتفاع 2 متر',
    inStock: true,
    lastUpdated: '2025-09-30',
  },
  {
    id: 'mesh-ajdar-150x150x8',
    name: 'مش آجدار 150×150×8',
    category: PRODUCT_CATEGORIES[10],
    subcategory: 'مش آجدار',
    brand: 'اصفهان',
    size: '150×150×8',
    price: 172000,
    unit: 'kg',
    weight: 35,
    description: 'مش آجدار تسلیح بتن - ابعاد ورق 2.15×5 متر',
    inStock: true,
    lastUpdated: '2025-09-30',
  },

  // مواد اولیه
  {
    id: 'ahan-esfonji-grade-a',
    name: 'آهن اسفنجی درجه A',
    category: PRODUCT_CATEGORIES[11],
    subcategory: 'آهن اسفنجی',
    brand: 'فولاد ثامن',
    size: 'Grade A',
    price: 145000,
    unit: 'kg',
    description: 'آهن اسفنجی درجه یک - درجه فلزی 92 درصد',
    inStock: true,
    lastUpdated: '2025-09-30',
  },
  {
    id: 'foro-aliazh-ferromangan',
    name: 'فروآلیاژ فرومنگنز',
    category: PRODUCT_CATEGORIES[11],
    subcategory: 'فروآلیاژ',
    brand: 'زاگرس',
    size: 'FeMn 75%',
    price: 385000,
    unit: 'kg',
    description: 'فروآلیاژ فرومنگنز - خلوص 75 درصد منگنز',
    inStock: true,
    lastUpdated: '2025-09-30',
  },
];
